# Generated by Django 5.1.1 on 2024-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
